-- Схема БД сервиса планирования маршрутов выездных инженеров.
-- Соответствует ТЗ «Билайн Бизнес», п. 2.4, 2.4.1, 2.4.2.

CREATE TYPE event_type AS ENUM (
    'urgent_request',          -- срочная заявка
    'request_cancellation',    -- отмена заявки
    'engineer_unavailability'  -- недоступность инженера
);

CREATE TYPE plan_run_type AS ENUM (
    'baseline',   -- базовый
    'optimized',  -- оптимизированный
    'replanned'   -- после перепланирования
);

-- ============================================================
-- Справочники (п. 2.4.1) — значения фиксированы ТЗ, не изменяются
-- ============================================================

CREATE TABLE skill (
    id   SMALLINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE transport (
    id   SMALLINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE priority (
    id   SMALLINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- ============================================================
-- Заявка
-- ============================================================

CREATE TABLE request (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude         NUMERIC(9, 6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude        NUMERIC(9, 6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    address          TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    window_start     TIMESTAMPTZ NOT NULL,
    window_end       TIMESTAMPTZ NOT NULL,
    priority_id      SMALLINT NOT NULL REFERENCES priority (id),
    skill_id         SMALLINT NOT NULL REFERENCES skill (id),
    transport_id     SMALLINT REFERENCES transport (id),
    CHECK (window_end > window_start)
);

CREATE INDEX request_priority_id_idx ON request (priority_id);
CREATE INDEX request_skill_id_idx ON request (skill_id);
CREATE INDEX request_transport_id_idx ON request (transport_id);
CREATE INDEX request_window_idx ON request (window_start, window_end);

-- ============================================================
-- Инженер
-- ============================================================

CREATE TABLE engineer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    start_latitude  NUMERIC(9, 6) NOT NULL CHECK (start_latitude BETWEEN -90 AND 90),
    start_longitude NUMERIC(9, 6) NOT NULL CHECK (start_longitude BETWEEN -180 AND 180),
    shift_start     TIMESTAMPTZ NOT NULL,
    shift_end       TIMESTAMPTZ NOT NULL,
    transport_id    SMALLINT NOT NULL REFERENCES transport (id),
    CHECK (shift_end > shift_start)
);

CREATE INDEX engineer_transport_id_idx ON engineer (transport_id);
CREATE INDEX engineer_shift_idx ON engineer (shift_start, shift_end);

-- Навыки инженера (многие-ко-многим, 1..3 навыка — контролируется наполнением/приложением)
CREATE TABLE engineer_skill (
    engineer_id BIGINT NOT NULL REFERENCES engineer (id) ON DELETE CASCADE,
    skill_id    SMALLINT NOT NULL REFERENCES skill (id),
    PRIMARY KEY (engineer_id, skill_id)
);

CREATE INDEX engineer_skill_skill_id_idx ON engineer_skill (skill_id);

-- ============================================================
-- Событие перепланирования
-- ============================================================

CREATE TABLE event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  event_type NOT NULL,
    event_time  TIMESTAMPTZ NOT NULL,
    request_id  BIGINT REFERENCES request (id),
    engineer_id BIGINT REFERENCES engineer (id),
    -- срочная заявка/отмена заявки ссылаются на request; недоступность инженера — на engineer
    CHECK (
        (event_type = 'engineer_unavailability' AND engineer_id IS NOT NULL AND request_id IS NULL)
        OR
        (event_type IN ('urgent_request', 'request_cancellation') AND request_id IS NOT NULL AND engineer_id IS NULL)
    )
);

CREATE INDEX event_request_id_idx ON event (request_id);
CREATE INDEX event_engineer_id_idx ON event (engineer_id);
CREATE INDEX event_event_time_idx ON event (event_time);

-- ============================================================
-- План и назначения (результат работы планировщика, п. 2.4.2)
-- ============================================================

CREATE TABLE plan (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type   plan_run_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX plan_created_at_idx ON plan (created_at);

CREATE TABLE assignment (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id              BIGINT NOT NULL REFERENCES plan (id) ON DELETE CASCADE,
    request_id           BIGINT NOT NULL REFERENCES request (id),
    engineer_id          BIGINT REFERENCES engineer (id),
    visit_order          INTEGER CHECK (visit_order > 0),
    planned_arrival_time TIMESTAMPTZ,
    unassigned_reason    TEXT,
    UNIQUE (plan_id, request_id),
    -- NULL engineer_id = заявка не назначена: порядок/время посещения тоже не определены
    CHECK (
        (engineer_id IS NULL AND visit_order IS NULL AND planned_arrival_time IS NULL)
        OR
        (engineer_id IS NOT NULL AND visit_order IS NOT NULL AND planned_arrival_time IS NOT NULL)
    )
);

CREATE INDEX assignment_plan_id_idx ON assignment (plan_id);
CREATE INDEX assignment_request_id_idx ON assignment (request_id);
CREATE INDEX assignment_engineer_id_idx ON assignment (engineer_id);

-- в рамках плана у инженера не может быть двух заявок с одинаковым порядком посещения
CREATE UNIQUE INDEX assignment_plan_engineer_order_uq
    ON assignment (plan_id, engineer_id, visit_order)
    WHERE engineer_id IS NOT NULL;
