-- Справочник офисов: откуда исполнители, как правило, выезжают на смену.
--
-- Офисы взяты из исходных CSV (`Обезличивание/* Синтетические данные.csv`): в конце каждого
-- файла строка «Адрес офиса». Название офиса — регион файла. Координаты найдены геокодером
-- OpenStreetMap (Nominatim): у Симферопольского проезда — точно по дому, у двух других OSM
-- знает дом только без строения, поэтому точка стоит на доме 83 к1 и 1 к1 соответственно.
-- Диспетчер может уточнить координаты в разделе «Справочники».
--
-- engineer.office_id — из какого офиса выезжает исполнитель. Координаты старта при этом
-- по-прежнему хранятся у исполнителя (их читают планировщик и снимки планов): бэкенд
-- копирует их из офиса при сохранении и переносит всем исполнителям офиса, когда у офиса
-- меняются координаты. Удалили офис — ссылка снимается (ON DELETE SET NULL), а старт
-- остаётся на прежнем месте как «своя точка».
BEGIN;

CREATE TABLE IF NOT EXISTS office (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT NOT NULL UNIQUE,
    address   TEXT NOT NULL,
    latitude  NUMERIC(9, 6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude NUMERIC(9, 6) NOT NULL CHECK (longitude BETWEEN -180 AND 180)
);
COMMENT ON TABLE office IS 'Офисы, из которых исполнители выезжают на смену';

INSERT INTO office (id, name, address, latitude, longitude) OVERRIDING SYSTEM VALUE VALUES
    (1, 'Восток',     'г. Москва, ул Юных Ленинцев, д 83с 4',  55.699798, 37.772576),
    (2, 'Юго-восток', 'г. Москва, ул Бирюлёвская, д 1с1',      55.602085, 37.665342),
    (3, 'Югоцентр',   'г. Москва, проезд Симферопольский, д 7', 55.664757, 37.615839)
ON CONFLICT (id) DO NOTHING;

-- явные номера выше не сдвигают счётчик — иначе следующий офис получил бы номер 1
SELECT setval(pg_get_serial_sequence('office', 'id'), (SELECT MAX(id) FROM office));

ALTER TABLE engineer
    ADD COLUMN IF NOT EXISTS office_id BIGINT REFERENCES office (id) ON DELETE SET NULL;
COMMENT ON COLUMN engineer.office_id IS
    'Офис, из которого выезжает исполнитель; NULL — старт в своей точке';
CREATE INDEX IF NOT EXISTS engineer_office_idx ON engineer (office_id);

COMMIT;
