-- Справочник оборудования и требование заявки к оборудованию.
--
-- equipment — типы оборудования, которые техник привозит на заявку. Для начала два типа,
-- оба есть в исходных заявках: роутер (подключения, переход на гигабит, дозаказ
-- оборудования) и ТВ-приставка («ТВ. Замена приставки техником»). Справочник правится
-- в интерфейсе: «Справочники» -> «Оборудование».
--
-- request.equipment_id — какое оборудование нужно для заявки; NULL — не нужно.
-- Удалить тип оборудования, который требуется заявкам, нельзя (внешний ключ без каскада):
-- иначе требование молча пропало бы у заявок.
BEGIN;

CREATE TABLE IF NOT EXISTS equipment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT ''
);
COMMENT ON TABLE equipment IS 'Типы оборудования, которые техник привозит на заявку';

INSERT INTO equipment (id, name, description) OVERRIDING SYSTEM VALUE VALUES
    (1, 'Роутер',       'Wi-Fi роутер: подключение, переход на гигабит, дозаказ оборудования'),
    (2, 'ТВ-приставка', 'Приставка цифрового ТВ: установка и замена техником')
ON CONFLICT (id) DO NOTHING;

-- явные номера выше не сдвигают счётчик — иначе следующий тип получил бы номер 1
SELECT setval(pg_get_serial_sequence('equipment', 'id'), (SELECT MAX(id) FROM equipment));

ALTER TABLE request ADD COLUMN IF NOT EXISTS equipment_id BIGINT REFERENCES equipment (id);
COMMENT ON COLUMN request.equipment_id IS 'Какое оборудование нужно для заявки; NULL — не нужно';
CREATE INDEX IF NOT EXISTS request_equipment_idx ON request (equipment_id);

COMMIT;
