-- Учётки диспетчеров и разделение данных по офисам.
--
-- Офис обслуживает свой регион, и диспетчер работает только с ним: заявки, бригады и планы
-- чужих офисов ему не видны. Офис не выбирается в интерфейсе, как день, — он приходит из
-- учётки: диспетчер привязан к офису, администратор выбирает офис сам.
--
-- app_user — учётки. role: admin (справочники, пользователи, любой офис) или dispatcher
-- (только свой офис). Пароль — хэш scrypt (backend/src/core/security.py). Первый
-- администратор: логин admin, пароль admin — смените его после первого входа.
--
-- Разделение по офисам:
--   request.office_id  — чья заявка. Новая получает офис того, кто её завёл или загрузил.
--   engineer.office_id — чья бригада (раньше поле значило «откуда выезжает»). Откуда
--                        выезжает, теперь говорит start_at_office: из своего офиса или из
--                        своей точки start_latitude/start_longitude.
--   plan.office_id     — чей план. Утверждается один план на офис и день, а не на день.
--
-- Существующие данные раскладываются по офисам по ближайшей точке: заявка — по адресу,
-- бригада — по старту, план — по офису большинства своих бригад. Всё можно поправить руками.
BEGIN;

CREATE TABLE IF NOT EXISTS app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('admin', 'dispatcher')),
    office_id     BIGINT REFERENCES office (id),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    -- диспетчер без офиса не видел бы ничего
    CHECK (role = 'admin' OR office_id IS NOT NULL)
);
COMMENT ON TABLE app_user IS 'Учётки: администраторы и диспетчеры офисов';

INSERT INTO app_user (id, login, name, password_hash, role) OVERRIDING SYSTEM VALUE VALUES
    (1, 'admin', 'Администратор',
     'scrypt$16384$8$1$aGFja2F0b24tb3B0LWFkbQ$KkKriaTtLOkvkdU1KbGJy_74DprBRr1VjSzV9pROmRMuIdYytDRR-mkayeJG9AuBHJWYmbBFth05y3wnRbLSwg',
     'admin')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('app_user', 'id'), (SELECT MAX(id) FROM app_user));

-- ближайший офис к точке: на широте Москвы градус долготы короче градуса широты (cos 55.7° ≈ 0.56)
CREATE OR REPLACE FUNCTION pg_temp.nearest_office(lat NUMERIC, lon NUMERIC) RETURNS BIGINT AS $$
    SELECT id FROM office
    ORDER BY (latitude - lat) ^ 2 + ((longitude - lon) * 0.56) ^ 2, id
    LIMIT 1
$$ LANGUAGE sql STABLE;

-- заявки
ALTER TABLE request ADD COLUMN IF NOT EXISTS office_id BIGINT REFERENCES office (id);
UPDATE request SET office_id = pg_temp.nearest_office(latitude, longitude) WHERE office_id IS NULL;
ALTER TABLE request ALTER COLUMN office_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS request_office_idx ON request (office_id);
COMMENT ON COLUMN request.office_id IS 'Офис, чья это заявка';

-- бригады: office_id теперь «чья бригада», а «из офиса ли старт» — отдельный флаг
-- флаг проставляется только при первом запуске: повторный прогон не должен объявить
-- «из офиса» всех бригад, которым офис уже назначен ниже
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'engineer' AND column_name = 'start_at_office'
    ) THEN
        ALTER TABLE engineer ADD COLUMN start_at_office BOOLEAN NOT NULL DEFAULT FALSE;
        UPDATE engineer SET start_at_office = TRUE WHERE office_id IS NOT NULL;
    END IF;
END
$$;
UPDATE engineer
SET office_id = pg_temp.nearest_office(start_latitude, start_longitude)
WHERE office_id IS NULL;
ALTER TABLE engineer ALTER COLUMN office_id SET NOT NULL;
-- раньше при удалении офиса ссылка снималась; теперь бригада без офиса невозможна
ALTER TABLE engineer DROP CONSTRAINT IF EXISTS engineer_office_id_fkey;
ALTER TABLE engineer ADD CONSTRAINT engineer_office_id_fkey FOREIGN KEY (office_id) REFERENCES office (id);
COMMENT ON COLUMN engineer.office_id IS 'Офис, чья это бригада';
COMMENT ON COLUMN engineer.start_at_office IS
    'Выезжает из своего офиса (старт = точка офиса) или из своей точки';

-- планы
ALTER TABLE plan ADD COLUMN IF NOT EXISTS office_id BIGINT REFERENCES office (id);
UPDATE plan p
SET office_id = (
    SELECT e.office_id
    FROM assignment a
    JOIN engineer e ON e.id = a.engineer_id
    WHERE a.plan_id = p.id
    GROUP BY e.office_id
    ORDER BY count(*) DESC, e.office_id
    LIMIT 1
)
WHERE office_id IS NULL;
UPDATE plan SET office_id = (SELECT MIN(id) FROM office) WHERE office_id IS NULL;
ALTER TABLE plan ALTER COLUMN office_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS plan_office_idx ON plan (office_id, plan_date);
COMMENT ON COLUMN plan.office_id IS 'Офис, чей это план';

-- один утверждённый план на офис и день: у каждого офиса свой день
DROP INDEX IF EXISTS plan_approved_day_idx;
CREATE UNIQUE INDEX IF NOT EXISTS plan_approved_office_day_idx
    ON plan (office_id, plan_date)
    WHERE approved_at IS NOT NULL;

COMMIT;
