-- Статус «В работе» и история статусов заявки.
--
-- «В работе» — бригада уже едет на заявку или работает на ней. Такая заявка зафиксирована:
-- в пересчёт плана она не идёт (plannable = FALSE), как и выполненная.
--
-- request_status_history — кто, когда и как менял статус заявки: из какого статуса в какой,
-- вручную (оператор) или системой (утверждение плана), по какому плану. Нужна, чтобы
-- разбирать пересчёты: что происходило с заявкой. from_status_id = NULL — заявка появилась.
-- Существующим заявкам ставится одна начальная запись с их текущим статусом.
BEGIN;

INSERT INTO request_status (id, code, name, plannable) VALUES
    (5, 'in_progress', 'В работе', FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO request_status_transition (from_status_id, to_status_id, manual, description) VALUES
    (2, 5, TRUE, 'Бригада выехала на заявку — в пересчёт она больше не идёт'),
    (5, 3, TRUE, 'Оператор отметил выполнение'),
    (5, 4, TRUE, 'Заявка отменена, когда бригада уже была в работе')
ON CONFLICT (from_status_id, to_status_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS request_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     BIGINT NOT NULL REFERENCES request (id) ON DELETE CASCADE,
    from_status_id SMALLINT REFERENCES request_status (id),
    to_status_id   SMALLINT NOT NULL REFERENCES request_status (id),
    changed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    manual         BOOLEAN NOT NULL,
    user_id        BIGINT REFERENCES app_user (id) ON DELETE SET NULL,
    plan_id        BIGINT REFERENCES plan (id) ON DELETE SET NULL,
    comment        TEXT NOT NULL DEFAULT ''
);
COMMENT ON TABLE request_status_history IS 'Смены статуса заявки: кто, когда, как и по какому плану';
COMMENT ON COLUMN request_status_history.from_status_id IS 'Прежний статус; NULL — заявка появилась';
COMMENT ON COLUMN request_status_history.manual IS 'TRUE — оператор, FALSE — система';
COMMENT ON COLUMN request_status_history.user_id IS 'Кто сменил статус или запустил действие (утверждение плана)';
CREATE INDEX IF NOT EXISTS request_status_history_request_idx
    ON request_status_history (request_id, changed_at);

INSERT INTO request_status_history (request_id, from_status_id, to_status_id, manual, plan_id, comment)
SELECT request.id, NULL, request.status_id, FALSE, request.approved_plan_id,
       'Статус на момент введения истории'
FROM request
WHERE NOT EXISTS (SELECT 1 FROM request_status_history WHERE request_id = request.id);

COMMIT;
