-- Справочник бригад.
--
-- Бригада — постоянный состав, работающий в регионе своего офиса. Строка engineer — это её
-- смена на конкретный день: при добавлении исполнителя на день выбирают бригаду из
-- справочника, а не пишут название руками (engineer.name остаётся копией названия бригады —
-- на него смотрят снимки планов и маршруты).
--
-- Вход в мобильное приложение — у бригады: логин и пароль задаются в справочнике бригад, как
-- у пользователей. Технически это учётка app_user с ролью brigade, привязанная к бригаде
-- (app_user.brigade_id) — вместо названия бригады (028).
BEGIN;

CREATE TABLE IF NOT EXISTS brigade (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id  BIGINT NOT NULL REFERENCES office (id),
    name       TEXT NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (office_id, name)
);
COMMENT ON TABLE brigade IS 'Бригады офиса: постоянный состав; смена на день — строка engineer';
COMMENT ON COLUMN brigade.is_active IS 'Выключенной бригаде не заводят новые смены и не пускают её в приложение';

-- бригады из уже заведённых смен: по названию в офисе
INSERT INTO brigade (office_id, name)
SELECT DISTINCT office_id, name FROM engineer
ON CONFLICT (office_id, name) DO NOTHING;

ALTER TABLE engineer ADD COLUMN IF NOT EXISTS brigade_id BIGINT REFERENCES brigade (id);
UPDATE engineer SET brigade_id = brigade.id
FROM brigade
WHERE engineer.brigade_id IS NULL AND brigade.office_id = engineer.office_id AND brigade.name = engineer.name;
ALTER TABLE engineer ALTER COLUMN brigade_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS engineer_brigade_idx ON engineer (brigade_id);
COMMENT ON COLUMN engineer.brigade_id IS 'Чья это смена: бригада из справочника';

-- учётка бригады привязана к бригаде, а не к названию
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS brigade_id BIGINT UNIQUE REFERENCES brigade (id) ON DELETE CASCADE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'app_user' AND column_name = 'brigade_name'
    ) THEN
        UPDATE app_user SET brigade_id = brigade.id
        FROM brigade
        WHERE app_user.role = 'brigade' AND brigade.office_id = app_user.office_id
          AND brigade.name = app_user.brigade_name;
        DELETE FROM app_user WHERE role = 'brigade' AND brigade_id IS NULL;
        ALTER TABLE app_user DROP CONSTRAINT IF EXISTS app_user_brigade_check;
        ALTER TABLE app_user DROP COLUMN brigade_name;
    END IF;
END
$$;
ALTER TABLE app_user DROP CONSTRAINT IF EXISTS app_user_brigade_check;
ALTER TABLE app_user ADD CONSTRAINT app_user_brigade_check
    CHECK ((role = 'brigade') = (brigade_id IS NOT NULL));
COMMENT ON COLUMN app_user.brigade_id IS 'Учётка бригады: вход в мобильное приложение этой бригады';

COMMIT;
